### ISSUE TITLE
Cifar-10 data add 90% symmetric noise

### ISSUE THREAD

**Issue by macaulishxcoo** [btsmart/bootstrapping-label-noise#1]
hello, In the paper, why did the Cifar-10 data add 90% symmetric noise (assuming extreme cases, such as ten dog images, of which nine predicted cats, birds, and so on, assuming these nine predicted for each of the other classes, so we only have one correctly classified, so which class should be used for model prediction), and the prediction results are still so high? How was it achieved?

**Comment by btsmart** [comment]
Hello,

Confusingly, at the moment there are two different conventions for what '90% symmetric label noise' means.

In our work, we follow the convention of works such as [DivideMix](https://arxiv.org/abs/2002.07394) (see Section 4.1), where 90% of the samples are taken and assigned random labels chosen uniformly from *all* classes in the dataset. This means that some samples are randomly 're-labelled' as their original, true class. For '90% symmetric label noise', 10% of samples are kept the same, and `90% * (1/num_classes)` are randomly re-labelled as their original class, which means that for CIFAR10, `10% + 90% * (1/10) = 19%` of samples keep their original labels, and only 81% of samples end up with an incorrect label. This convention is often used so that '100% symmetric label noise' refers to the case where every sample is equally likely to be labelled as any class.

The other convention (as mentioned in the DivideMix paper), is where 90% of the samples are taken and assigned random labels chosen uniformly from all *other* classes in the dataset. I believe this is what you are describing, and it is more intuitive because it means 90% of samples are mislabelled in '90% symmetric label noise'. In this convention, for CIFAR10, '90% symmetric label noise' refers to the case where every sample is equally likely to be labelled as any class.

In the second case, as you suggest, I think it would be impossible for any model to do better than random guessing. But in the first case, 19% of dogs are labelled as dogs, whereas only 9% of dogs are mislabelled as cats, or as birds, etc., so we are still able to learn a good model.

Hopefully this helps, the two different conventions make this needlessly confusing unfortunately.
